export enum EmailTemplateEvent {
  WHEN_NEW_UESR_CREATES = "1",
  WHEN_NEW_TASK_ASSIGNED = "2",
  SEND_ESTIMATION_TO_CUSTOMER = "3",
  GREETINGS_WHEN_ACCEPT_OFFER = "4r",
  CONTRACT_TO_CUSTOMER = "5",
}
